DELETE FROM tb1Second;
SELECT * FROM tb1Second;
INSERT INTO tb1Second VALUES (234,8.5), (12, 3.0);
SELECT * FROM tb1Second;
TRUNCATE TABLE tb1Second;
SELECT * FROM tb1Second;
DROP TABLE tb1Second;


DELETE tb1Second;
SELECT * FROM tb1Second;